name: Free VPS

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start VPS
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo service ssh start

          echo "root:123456" | sudo chpasswd

          sudo sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh restart

          curl -s https://api.ipify.org

          sleep 21600
